name: "Build"

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Upload results (SARIF)
  if: always()
  uses: github/codeql-action/upload-sarif@v2
  with:
    sarif_file: reports/report.sarif
